#!/bin/bash
set -euo pipefail

source ./assert.sh
source ./start-fresh.sh >/dev/null

echo
echo ==============================================================

#
# Compare the table columns between two schemas in the same database
#
./populate-db.sh db1 "
    CREATE SCHEMA s1;
    CREATE TABLE s1.table9 (
        id integer,
        name varchar(50)
    );
    CREATE TABLE s1.table10 (id bigint);
    CREATE TABLE s1.table11 ();

    CREATE SCHEMA s2;
    CREATE TABLE s2.table9 (
        id integer
    );
    CREATE TABLE s2.table10 (id integer);
    CREATE TABLE s2.table11 (id integer);
    CREATE OR REPLACE VIEW s1.view1 AS
        SELECT *
        FROM s1.table10;
"

echo
echo "# Compare the columns between two schemas in the same database"
echo "# Expect SQL:"
echo "#   Add s2.table9.name"
echo "#   Change s2.table10.id to bigint"
echo "#   Drop s2.table11.id"
echo

output=$(../pgdiff -U "u1" -W "asdf" -H "localhost" -D "db1" -S "s1" -O "sslmode=disable" \
                  -u "u1" -w "asdf" -h "localhost" -d "db1" -s "s2" -o "sslmode=disable" \
                  TABLE_COLUMN | clean_pgdiff_output)
assert_contains "$output" "ALTER TABLE s2.table9 ADD COLUMN name character varying(50);"
assert_contains "$output" "ALTER TABLE s2.table10 ALTER COLUMN id TYPE bigint;"
assert_contains "$output" "ALTER TABLE s2.table11 DROP COLUMN IF EXISTS id;"
assert_not_contains "$output" "view1"
printf '%s\n' "$output"

echo
echo ==============================================================

./populate-db.sh db2 "
    CREATE SCHEMA s1;
    CREATE TABLE s1.table9 (
        id integer,
        name varchar(40)
    );
    CREATE TABLE s1.table10 ();
    CREATE TABLE s1.table11 (dropme integer);

    CREATE SCHEMA s2;
    CREATE TABLE s2.table9 (
        id integer
    );
    CREATE TABLE s2.table10 (id integer);
    CREATE TABLE s2.table11 (id integer);
    CREATE OR REPLACE VIEW s1.view1 AS
        SELECT *
        FROM s1.table10;
"

echo
echo "# Compare the table columns in all schemas between two databases"
echo "# Expect:"
echo "#   Change s1.table9.name to varchar(50) "
echo "#   Add s1.table10.id"
echo "#   Drop s1.table11.dropme"
echo

output=$(../pgdiff -U "u1" -W "asdf" -H "localhost" -D "db1" -S "*" -O "sslmode=disable" \
                  -u "u1" -w "asdf" -h "localhost" -d "db2" -s "*" -o "sslmode=disable" \
                  TABLE_COLUMN | clean_pgdiff_output)
assert_contains "$output" "ALTER TABLE s1.table9 ALTER COLUMN name TYPE character varying(50);"
assert_contains "$output" "ALTER TABLE s1.table10 ADD COLUMN id integer;"
assert_contains "$output" "ALTER TABLE s1.table11 DROP COLUMN IF EXISTS dropme;"
assert_not_contains "$output" "view1"
printf '%s\n' "$output"
echo
