#!/bin/bash
set -euo pipefail

source ./assert.sh
source ./start-fresh.sh >/dev/null

echo
echo ==========================================================
echo

#
# Compare the grants between two schemas in the same database
#

./populate-db.sh db1 "
    CREATE SCHEMA s1;
    CREATE SCHEMA s2;

    CREATE TABLE s1.table1 (id integer, name varchar(30));
    GRANT SELECT, UPDATE (name) ON s1.table1 TO u2;

    CREATE TABLE s2.table1 (id integer, name varchar(30));
    GRANT SELECT, REFERENCES (name) ON s2.table1 TO u2;

    CREATE TABLE s1.table2 (id integer, name varchar(30));

    CREATE TABLE s2.table2 (id integer, name varchar(30));
    GRANT SELECT (name) ON s2.table2 TO u2;

    CREATE TABLE s1.table3 (id integer, name varchar(30));
    GRANT SELECT (name) ON s1.table3 TO u2;

    CREATE TABLE s2.table3 (id integer, name varchar(30));

    CREATE TABLE s1.table4 (id integer, name varchar(30));
    GRANT SELECT (name) ON s1.table4 TO u2 WITH GRANT OPTION;

    CREATE TABLE s2.table4 (id integer, name varchar(30));
    GRANT SELECT (name) ON s2.table4 TO u2;

    CREATE TABLE s1.table5 (id integer, name varchar(30));
    GRANT SELECT (name) ON s1.table5 TO u2;

    CREATE TABLE s2.table5 (id integer, name varchar(30));
    GRANT SELECT (name) ON s2.table5 TO u2 WITH GRANT OPTION;
"

echo
echo "# Compare the grants between two schemas in the same database"
echo "# Expect normal attribute diffs plus grant-option upgrade/downgrade"
echo

output=$(../pgdiff -U "u1" -W "asdf" -H "localhost" -D "db1" -S "s1" -O "sslmode=disable" \
                  -u "u1" -w "asdf" -h "localhost" -d "db1" -s "s2" -o "sslmode=disable" \
                  GRANT_ATTRIBUTE | clean_pgdiff_output)
assert_contains "$output" "GRANT UPDATE (name) ON s2.table1 TO u2; -- Change"
assert_contains "$output" "REVOKE REFERENCES (name) ON s2.table1 FROM u2; -- Change"
assert_contains "$output" "REVOKE SELECT (name) ON s2.table2 FROM u2; -- Drop"
assert_contains "$output" "GRANT SELECT (name) ON s2.table3 TO u2; -- Add"
assert_contains "$output" "GRANT SELECT (name) ON s2.table4 TO u2 WITH GRANT OPTION; -- Change"
assert_contains "$output" "REVOKE GRANT OPTION FOR SELECT (name) ON s2.table5 FROM u2; -- Change"
printf '%s\n' "$output"

echo
echo ==========================================================
echo

source ./start-fresh.sh >/dev/null

#
# Compare the grants in all schemas between two databases
#

./populate-db.sh db1 "
    CREATE SCHEMA s1;
    CREATE SCHEMA s2;
    CREATE TABLE s1.table1 (id integer, name varchar(30));
    GRANT SELECT, UPDATE (name) ON s1.table1 TO u2;

    CREATE TABLE s2.table1 (id integer, name varchar(30));
    GRANT UPDATE (name) ON s2.table1 TO u2;

    CREATE TABLE s2.table3 (id integer, name varchar(30));

    CREATE TABLE s2.table4 (id integer, name varchar(30));
    GRANT SELECT, UPDATE (name) ON s2.table4 TO u2;
"

./populate-db.sh db2 "
    CREATE SCHEMA s1;
    CREATE SCHEMA s2;
    CREATE TABLE s1.table1 (id integer, name varchar(30));
    GRANT SELECT, UPDATE (name) ON s1.table1 TO u2;
    GRANT SELECT (id) ON s1.table1 TO u2;

    CREATE TABLE s2.table1 (id integer, name varchar(30));
    GRANT REFERENCES (name) ON s2.table1 TO u2;

    CREATE TABLE s2.table3 (id integer, name varchar(30));
    GRANT UPDATE (name) ON s2.table3 TO u2;

    CREATE TABLE s2.table4 (id integer, name varchar(30));
"

echo
echo "# Compare the grants in all schemas between two databases"
echo "# Expect SQL (pseudocode):"
echo "#   Revoke SELECT     (id)   on s1.table1 for u2"
echo "#   Grant  UPDATE     (name) on s2.table1 for u2"
echo "#   Revoke REFERENCES (name) on s2.table1 for u2"
echo "#   Revoke UPDATE     (name) on s2.table3 for u2"
echo "#   Grant  UPDATE     (name) on s2.table4 for u2"
echo

output=$(../pgdiff -U "u1" -W "asdf" -H "localhost" -D "db1" -S "*" -O "sslmode=disable" \
                  -u "u1" -w "asdf" -h "localhost" -d "db2" -s "*" -o "sslmode=disable" \
                  GRANT_ATTRIBUTE | clean_pgdiff_output)
assert_contains "$output" "REVOKE SELECT (id) ON s1.table1 FROM u2; -- Drop"
assert_contains "$output" "GRANT UPDATE (name) ON s2.table1 TO u2; -- Change"
assert_contains "$output" "REVOKE REFERENCES (name) ON s2.table1 FROM u2; -- Change"
assert_contains "$output" "REVOKE UPDATE (name) ON s2.table3 FROM u2; -- Drop"
assert_contains "$output" "GRANT UPDATE (name) ON s2.table4 TO u2; -- Add"
printf '%s\n' "$output"
echo
echo
