#!/bin/bash
set -euo pipefail

source ./assert.sh
source ./start-fresh.sh >/dev/null

echo
echo ==========================================================
echo

./populate-db.sh db1 "
    CREATE SCHEMA s1;
    CREATE SCHEMA s2;
    CREATE TABLE s1.table1 (id integer, name varchar(30));
    CREATE TABLE s2.table1 (id integer, name varchar(30));

    CREATE VIEW s1.view_add AS SELECT id FROM s1.table1;
    CREATE VIEW s1.view_change AS SELECT id FROM s1.table1;
    CREATE VIEW s1.view_same AS SELECT id FROM s1.table1;

    CREATE VIEW s2.view_change AS SELECT name FROM s2.table1;
    CREATE VIEW s2.view_drop AS SELECT id FROM s2.table1;
    CREATE VIEW s2.view_same AS SELECT id FROM s1.table1;
"

output=$(../pgdiff -U "u1" -W "asdf" -H "localhost" -D "db1" -S "s1" -O "sslmode=disable" \
                  -u "u1" -w "asdf" -h "localhost" -d "db1" -s "s2" -o "sslmode=disable" \
                  VIEW | clean_pgdiff_output)
assert_contains "$output" "CREATE VIEW s2.view_add AS"
assert_contains "$output" "DROP VIEW s2.view_change;"
assert_contains "$output" "CREATE VIEW s2.view_change AS"
assert_contains "$output" "DROP VIEW s2.view_drop;"
printf '%s\n' "$output"

echo
echo ==========================================================
echo

./populate-db.sh db2 "
    CREATE SCHEMA s1;
    CREATE SCHEMA s2;
    CREATE TABLE s1.table1 (id integer);
    CREATE TABLE s2.table1 (id integer);

    CREATE VIEW s2.view_keep AS SELECT id FROM s2.table1;
    CREATE VIEW s2.view_drop AS SELECT id FROM s2.table1;
"

output=$(../pgdiff -U "u1" -W "asdf" -H "localhost" -D "db1" -S "*" -O "sslmode=disable" \
                  -u "u1" -w "asdf" -h "localhost" -d "db2" -s "*" -o "sslmode=disable" \
                  VIEW | clean_pgdiff_output)
assert_contains "$output" "CREATE VIEW s1.view_add AS"
assert_contains "$output" "DROP VIEW s2.view_drop;"
printf '%s\n' "$output"
